app:
  data:
    signals:
      1:
        - setUp
        - setAlgoParam 1 60
        - performCalc
        - submitToMarket
      2:
        - reverse
        - setAlgoParam 1 80
        - submitToMarket
      3:
        - setAlgoParam 1 90
        - setAlgoParam 2 15
        - performCalc
        - submitToMarket
